- name: Agent Configuration
  hosts: ilahyaniSW
  gather_facts: false
  become: true
  vars_files:
    - "{{ playbook_dir }}/../vars/node_token.yml"
  tasks:
    - name: Debugggggggggggggg
      ansible.builtin.debug:
        msg: "token>>>>>>> {{ node_token }}"
    - name: Install K3S Agent
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN={{ node_token }} sh -
      args:
        executable: /bin/bash
    # - name: Enable K3S service
    #   ansible.builtin.systemd:
    #     name: k3s
    #     enabled: true
    #     state: started
    # - name: Wait for K3S to start
    #   ansible.builtin.wait_for:
    #     port: 6443
    #     state: started
    #     timeout: 30
