apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      item: database
  template:
    metadata:
      labels:
        item: database
    spec:
      containers:
        - name: database
          image: redis
          ports:
            - containerPort: 6379
          command: ["redis-server", "--protected-mode", "no", "--bind", "0.0.0.0"]
          volumeMounts:
            - mountPath: "/data"
              name: wai-storage
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "256Mi"
          #     cpu: "250m"
      volumes:
        - name: wai-storage
          persistentVolumeClaim:
            claimName: wai-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ClusterIP
  selector:
    item: database
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wai-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/wai-v"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wai-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
