apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo42
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://GITLAB_HOST:9090/root/iot.git/
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
