apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      item: gitlab
  template:
    metadata:
      labels:
        item: gitlab
    spec:
      containers:
        - name: gitlab-ce
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
spec:
  selector:
    item: gitlab
  ports:
     - protocol: TCP
       port: 8081
       targetPort: 80
