apiVersion: apps/v1
kind: Deployment
metadata:
  name: will42-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      item: will42
  template:
    metadata:
      labels:
        item: will42
    spec:
      containers:
        - name: will
          image: wil42/playground:v1
          ports:
            - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: will42-service
spec:
  selector:
    item: will42
  ports:
     - protocol: TCP
       port: 8888
       targetPort: 8888
