- name: Agent Configuration
  hosts: ilahyaniSW
  gather_facts: false
  become: true
  vars_files:
    - "{{ playbook_dir }}/../vars/node_token.yml"
  tasks:
    - name: Verify Node Token From Agent
      ansible.builtin.debug:
        msg: "{{ node_token }}"
    - name: Install K3S Agent
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN={{ node_token }} sh -
      args:
        executable: /bin/bash
