Vagrant.configure("2") do |config|

    config.vm.define "ilahyaniS" do |ilahyaniS|
        ilahyaniS.vm.box = "bento/ubuntu-22.04"
        ilahyaniS.vm.hostname = "ilahyaniS"
        ilahyaniS.vm.network "private_network", ip: "192.168.56.110", interface: "eth1", hostname: true
        ilahyaniS.vm.provider "vmware_desktop" do |v|
            v.memory = 1024
            v.cpus = 2
        end
        # ilahyaniS.vm.provider "virtualbox" do |v|
        #     v.memory = 1024
        #     v.cpus = 2
        # end
        ilahyaniS.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/playbooks/server.yml"
        end
    end

    config.vm.define "ilahyaniSW" do |ilahyaniSW|
        ilahyaniSW.vm.box = "bento/ubuntu-22.04"
        ilahyaniSW.vm.hostname = "ilahyaniSW"
        ilahyaniSW.vm.network "private_network", ip: "192.168.56.111", interface: "eth1", hostname: true
        ilahyaniSW.vm.provider "vmware_desktop" do |v|
            v.memory = 1024
            v.cpus = 2
        end
        # ilahyaniSW.vm.provider "virtualbox" do |v|
        #     v.memory = 1024
        #     v.cpus = 2
        # end
        ilahyaniSW.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/playbooks/agent.yml"
        end
    end

end