- name: Server Configuration
  hosts: ilahyaniS
  gather_facts: false
  become: true
  vars_files:
    - ./vars/apps.yaml
  tasks:
    - name: Install K3S Server
      ansible.builtin.shell: |
        if [ -f /etc/rancher/k3s/k3s ]; then
          echo "K3S is already installed"
        else
          curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
        fi
      args:
        executable: /bin/bash
    - name: Verify K3S Installation
      command: kubectl get nodes
      register: k3s_output
      changed_when: false
    - name: Display K3S Status
      debug:
        msg: "{{ k3s_output.stdout_lines }}"
    - name: Create directory for manifests
      ansible.builtin.file:
        path: /home/vagrant/manifests
        state: directory
        mode: '0755'
    - name: Generate Deployment Manifests
      ansible.builtin.template:
        src: ./templates/manifest.yaml.j2
        dest: /home/vagrant/manifests/{{ item.name }}.yaml
      loop: "{{ apps }}"
    - name: Deploy Applicaitons
      ansible.builtin.shell:
        cmd: kubectl apply -f /home/vagrant/manifests
      register: output
      failed_when: output.rc != 0
