name: Build and Push

on:
  push:
    tags:
      - 'v*'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Paths Filter
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'app/frontend/**'
            backend:
              - 'app/backend/**'

  build-frontend:
    needs: filter
    if: needs.filter.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      # Your frontend build steps here
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: Extract Tag Name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: app/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/whoami_frontend:${{ env.TAG }}

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|whoami_frontend:.*|whoami_frontend:${{ env.TAG }}|g" k8s/dev/frontend.yaml || exit 1
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update frontend image to ${{ env.TAG }}"
          git push origin HEAD:main


  build-backend:
    needs: filter
    if: needs.filter.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      # Your backend build steps here
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: Extract Tag Name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: app/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/whoami_backend:${{ env.TAG }}

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|whoami_backend:.*|whoami_backend:${{ env.TAG }}|g" k8s/dev/backend.yaml || exit 1
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update backend image to ${{ env.TAG }}"
          git push origin HEAD:main
