name: Update Backend Image

on:
    push:
        branches:
            - 'main'
        paths:
            - 'app/backend/**'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Login to Dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWD }}
            
            - name: Extract Tag Name
              id: get_tag
              run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            
            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: app/backend
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/whoami_backend:${{ env.TAG }}

            - name: Update Kubernetes Manifests
              run: |
                sed -i "s|whoami_backend:.*|whoami_backend:${{ env.TAG }}|g" k8s/dev/backend.yaml || exit 1
            - name: Commit and Push Changes
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git commit -am "Update backend image to ${{ env.TAG }}"
                git push origin HEAD:main
